import type { EvidenceBundle } from "../evidence/model.js";
import type { Verdict } from "../oracle/schema.js";
import type { ClusterResult } from "../oracle/cluster.js";

const VERDICT_CLASS: Record<Verdict["verdict"], string> = {
  PASS: "pass",
  REGRESSION: "regression",
  FAIL: "fail",
  UNCERTAIN: "uncertain",
};

export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function evidenceList(
  entries: Verdict["supportingEvidence"],
  heading: string,
): string {
  if (entries.length === 0) return "";
  return `<section><h2>${heading}</h2><ul class="evidence">${entries
    .map(
      (e) =>
        `<li>${escapeHtml(e.observation)} <span class="refs">(${escapeHtml(
          e.evidenceIds.join(", ") || "n/a",
        )})</span></li>`,
    )
    .join("")}</ul></section>`;
}

/** Self-contained per-test evidence report. Screenshots resolve relatively (assets/…). */
export function renderHtmlReport(bundle: EvidenceBundle, verdict: Verdict): string {
  const passed = bundle.assertions.filter((a) => a.passed).length;
  const screenshots = bundle.evidence.filter((e) => e.type === "screenshot");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${escapeHtml(bundle.title)} — Visual Reviewer</title>
<style>
  :root { color-scheme: light dark; }
  body { font-family: system-ui, sans-serif; max-width: 60rem; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }
  .badge { display: inline-block; padding: .2rem .7rem; border-radius: 999px; font-weight: 700; }
  .pass .badge { background: #dcfce7; color: #14532d; }
  .regression .badge, .fail .badge { background: #fee2e2; color: #7f1d1d; }
  .uncertain .badge { background: #fef9c3; color: #713f12; }
  .meta { color: gray; font-size: .9rem; }
  section { margin: 1.5rem 0; }
  h2 { border-bottom: 1px solid #8884; padding-bottom: .25rem; }
  .evidence li { margin: .35rem 0; }
  .refs { color: gray; font-family: ui-monospace, monospace; font-size: .85em; }
  .shots img { max-width: 100%; border: 1px solid #8886; margin: .5rem 0; }
  footer { margin-top: 3rem; color: gray; font-size: .85rem; }
</style>
</head>
<body class="${VERDICT_CLASS[verdict.verdict]}">
<header>
  <span class="badge">${verdict.verdict}</span>
  <strong>${Math.round(verdict.confidence * 100)}% confidence</strong>
  <h1>${escapeHtml(bundle.title)}</h1>
  <p class="meta"><code>${escapeHtml(bundle.file)}</code> · deterministic: ${bundle.status}, ${passed}/${bundle.assertions.length} assertions passed</p>
</header>

<section><h2>Intent</h2><p>${escapeHtml(verdict.intentSummary)}</p></section>
<section><h2>Why</h2><p>${escapeHtml(verdict.reasoning)}</p></section>
${evidenceList(verdict.supportingEvidence, "Supporting evidence")}
${evidenceList(verdict.suspiciousObservations, "Suspicious observations")}
${
  verdict.suggestedNextStep
    ? `<section><h2>Suggested next step</h2><p>${escapeHtml(verdict.suggestedNextStep)}</p></section>`
    : ""
}
${
  screenshots.length > 0
    ? `<section class="shots"><h2>Screenshots (${screenshots.length})</h2>${screenshots
        .map((s) => {
          const file = (s.content as { file?: string }).file ?? "";
          return `<figure><img loading="lazy" src="${escapeHtml(file)}" alt="${escapeHtml(
            String(s.metadata?.name ?? s.id),
          )}"><figcaption>${escapeHtml(String(s.metadata?.name ?? s.id))} [${escapeHtml(s.id)}]</figcaption></figure>`;
        })
        .join("")}</section>`
    : ""
}
<footer>Advisory-only verdict — this report never fails CI on its own. Generated by visual-reviewer.</footer>
</body>
</html>`;
}

export interface IndexEntry {
  title: string;
  /** Path to the per-test HTML report, relative to the index location. */
  href: string;
  verdict?: Verdict["verdict"];
  error?: string;
}

/** Run-level index linking every judged test's report. */
export function renderHtmlIndex(entries: IndexEntry[], clusters?: ClusterResult): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Visual Reviewer — Run Report</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 50rem; margin: 2rem auto; padding: 0 1rem; }
  table { border-collapse: collapse; width: 100%; }
  td, th { text-align: left; padding: .45rem .6rem; border-bottom: 1px solid #8884; }
  .PASS { color: #15803d; } .REGRESSION, .FAIL { color: #b91c1c; font-weight: 700; } .UNCERTAIN { color: #a16207; }
  .ERROR { color: #b91c1c; }
</style>
</head>
<body>
<h1>Visual Reviewer — Run Report</h1>
${
  clusters && clusters.clusters.length > 0
    ? `<section><h2>Likely root causes</h2>${clusters.clusters
        .map(
          (c) =>
            `<p>🔗 <code>${escapeHtml(c.label)}</code> — ${c.tests.length} test(s): ${escapeHtml(
              [...new Set(c.tests.map((t) => t.title))].join(", "),
            )}</p>`,
        )
        .join("")}</section>`
    : ""
}
<table><tr><th>Verdict</th><th>Test</th></tr>
${entries
  .map(
    (e) =>
      `<tr><td class="${e.verdict ?? "ERROR"}">${e.verdict ?? "JUDGE ERROR"}</td>` +
      `<td><a href="${escapeHtml(e.href)}">${escapeHtml(e.title)}</a>${
        e.error ? ` <span style="color:gray">${escapeHtml(e.error.split("\n")[0])}</span>` : ""
      }</td></tr>`,
  )
  .join("\n")}
</table>
<p style="color:gray;font-size:.85rem">Advisory-only. Generated by visual-reviewer.</p>
</body>
</html>`;
}
