import type { EvidenceBundle } from "../evidence/model.js";
import type { Verdict } from "../oracle/schema.js";
import type { ClusterResult } from "../oracle/cluster.js";
import { renderClusterSummary } from "../oracle/cluster.js";

const VERDICT_ICON: Record<Verdict["verdict"], string> = {
  PASS: "✅",
  REGRESSION: "🚨",
  FAIL: "❌",
  UNCERTAIN: "⚠️",
};

function evidenceSection(entries: Verdict["supportingEvidence"], heading: string): string {
  if (entries.length === 0) return "";
  return `\n### ${heading}\n\n${entries
    .map((e) => `- ${e.observation} _(evidence: ${e.evidenceIds.join(", ") || "n/a"})_`)
    .join("\n")}\n`;
}

export function renderMarkdownReport(
  bundle: EvidenceBundle,
  verdict: Verdict,
  baseline?: { date: string; verdict: string; confidence: number } | null,
): string {
  const passed = bundle.assertions.filter((a) => a.passed).length;
  return `# Visual Reviewer — Evidence Report

**Test:** ${bundle.title}
**File:** \`${bundle.file}\`
**Deterministic result:** ${bundle.status} — ${passed}/${bundle.assertions.length} assertions passed

## AI Verdict

${VERDICT_ICON[verdict.verdict]} **${verdict.verdict}** — ${Math.round(verdict.confidence * 100)}% confidence

> ${verdict.intentSummary}
${
  baseline
    ? `
**Baseline:** compared against previous run from ${baseline.date} — previous AI verdict ${baseline.verdict} (${Math.round(baseline.confidence * 100)}%).
`
    : ""
}

## Why

${verdict.reasoning}
${evidenceSection(verdict.supportingEvidence, "Supporting evidence")}${evidenceSection(
    verdict.suspiciousObservations,
    "Suspicious observations",
  )}
${verdict.suggestedNextStep ? `## Suggested next step\n\n${verdict.suggestedNextStep}\n` : ""}
---
*Advisory-only verdict. This report never fails CI on its own. Generated by visual-reviewer.*
`;
}

export function renderRunSummary(
  judgements: Array<{ bundlePath: string; verdict?: Verdict; error?: string }>,
  clusters?: ClusterResult,
): string {
  const lines = ["", "── visual-reviewer (advisory) " + "─".repeat(30)];
  for (const j of judgements) {
    const title = j.verdict ? "" : "";
    if (j.verdict) {
      lines.push(
        `  ${VERDICT_ICON[j.verdict.verdict]} ${j.verdict.verdict.padEnd(11)} ${Math.round(
          j.verdict.confidence * 100,
        )}%  ${title || j.bundlePath}`,
      );
    } else {
      lines.push(`  ⚠️  JUDGE ERROR  ${j.error?.split("\n")[0]}`);
    }
  }
  if (clusters) {
    const clusterLines = renderClusterSummary(clusters);
    if (clusterLines) lines.push(clusterLines);
  }
  lines.push("  Reports: .visual-reviewer/**/report.md");
  return lines.join("\n");
}
